In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,21)

In [3]:
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
print(np.sum(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

210
10.5
10.5
5.766281297335398


In [8]:
indices_gt10 = np.where(arr1>10)[0]

In [9]:
print(indices_gt10)

[10 11 12 13 14 15 16 17 18 19]


In [10]:
### TASK 2

In [11]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
print("Transpose:")
print(arr2.T)

Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [14]:
print(arr2.sum(axis=1))

[10 26 42 58]


In [15]:
print(arr2.sum(axis=0))

[28 32 36 40]


In [16]:
### TASK 3

In [19]:
A = np.random.randint(1,21,size=(3,3))
B = np.random.randint(1,21,size=(3,3))
print("A:",A)
print("\nB:",B)

A: [[ 5  6  4]
 [ 5 17 13]
 [14 17 16]]

B: [[14 20  2]
 [ 7 20 10]
 [13 17 14]]


In [20]:
print(A+B)
print(A-B)
print(A*B)

[[19 26  6]
 [12 37 23]
 [27 34 30]]
[[ -9 -14   2]
 [ -2  -3   3]
 [  1   0   2]]
[[ 70 120   8]
 [ 35 340 130]
 [182 289 224]]


In [21]:
print(np.dot(A,B))

[[164 288 126]
 [358 661 362]
 [523 892 422]]


In [22]:
### TASK 4

In [25]:
arr1d = np.arange(1,13)
print(arr1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
arr2d= (arr1d.reshape(3,4))
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
sliced = arr2d[:2,-2:]
print(sliced)

[[3 4]
 [7 8]]
